services:
  sdnext:
    image: sdnext:latest
    user: $UID:$GID
    ports:
      - "7860:7860"
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: /NAS/sdout
        target: /outputs/
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
